// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test-share": {
    params: {};
  };
  "/generate-did": {
    params: {};
  };
  "/api/photos/upload": {
    params: {};
  };
  "/api/photos/share": {
    params: {};
  };
  "/api/photos/revoke": {
    params: {};
  };
  "/api/photos/shared/:cid": {
    params: {
      "cid": string;
    };
  };
  "/api/photos/download/:cid": {
    params: {
      "cid": string;
    };
  };
  "/photo/:cid": {
    params: {
      "cid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test-share" | "/generate-did" | "/api/photos/upload" | "/api/photos/share" | "/api/photos/revoke" | "/api/photos/shared/:cid" | "/api/photos/download/:cid" | "/photo/:cid";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/test-share.tsx": {
    id: "routes/test-share";
    page: "/test-share";
  };
  "routes/generate-did.tsx": {
    id: "routes/generate-did";
    page: "/generate-did";
  };
  "routes/api.photos.upload.tsx": {
    id: "routes/api.photos.upload";
    page: "/api/photos/upload";
  };
  "routes/api.photos.share.tsx": {
    id: "routes/api.photos.share";
    page: "/api/photos/share";
  };
  "routes/api.photos.revoke.tsx": {
    id: "routes/api.photos.revoke";
    page: "/api/photos/revoke";
  };
  "routes/api.photos.shared.$cid.tsx": {
    id: "routes/api.photos.shared.$cid";
    page: "/api/photos/shared/:cid";
  };
  "routes/api.photos.download.$cid.tsx": {
    id: "routes/api.photos.download.$cid";
    page: "/api/photos/download/:cid";
  };
  "routes/photo.$cid.tsx": {
    id: "routes/photo.$cid";
    page: "/photo/:cid";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/test-share": typeof import("./app/routes/test-share.tsx");
  "routes/generate-did": typeof import("./app/routes/generate-did.tsx");
  "routes/api.photos.upload": typeof import("./app/routes/api.photos.upload.tsx");
  "routes/api.photos.share": typeof import("./app/routes/api.photos.share.tsx");
  "routes/api.photos.revoke": typeof import("./app/routes/api.photos.revoke.tsx");
  "routes/api.photos.shared.$cid": typeof import("./app/routes/api.photos.shared.$cid.tsx");
  "routes/api.photos.download.$cid": typeof import("./app/routes/api.photos.download.$cid.tsx");
  "routes/photo.$cid": typeof import("./app/routes/photo.$cid.tsx");
};